redirect_me

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -5,6 +5,22 @@ if [[ $# -ne 4 ]]
 
 then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit
+    exit 1
 fi
+# assign parameters to the variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+# disabling strict host key checking
+
 scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE TRANSFER WAS COMPLETED SUCCESSFULLY"
+else	
+	echo "FILE TRANSFER FAILED"
+fi
